### ISSUE TITLE
Some Error on PlatformIO

### ISSUE THREAD

**Issue by Majid-Derhambakhsh** [ayushsharma82/NetWizard#14]
Hello

PlatformIO can't compile correctly the code, i found these bugs in compiling via PlatformIO:
1- AsyncTCP RP2040W was added to the project and error when compiling it (I fixed it by removing reference from platformio.ini at AsyncTCP library)
2- Some WiFi class member was not found in PlatformIO, such as WiFi.AP.localIP(), i updated the ESP package to the latest version but this error was not fixed

**Comment by ayushsharma82** [comment]
@Majid-Derhambakhsh 

Regarding 1st error, the solution was already in docs. Ref: https://docs.netwizard.pro/docs/intro/installation#modifications-in-platform-io-ini . **NOTE: It's necessary to delete .pio folder after adding these lines.**

Now coming to your 2nd error, that's because default espressif32 platform on PIO doesn't contain the latest Arduino SDK. You can easily get around it by using a fork platform that has latest features. Just like we did here: https://github.com/livegrid/OpenMatrix/blob/main/platformio.ini#L12
